version: '3.8'

services:
  kanban-db:
    restart: always
    container_name: kanban-db
    image: postgres:latest
    environment:
      POSTGRES_DB: kanbanapp_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - kanban-net

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5291:5291"
    environment:
      - ASPNETCORE_URLS=http://+:5291
    networks:
      - kanban-net
    depends_on:
      - kanban-db

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    networks:
      - kanban-net

networks:
  kanban-net:
    driver: bridge
